logo: # add logo name
title: MiRimonti - A spasso fra i monti
description: > # this means to ignore newlines until "baseurl:"
  Diario di passeggiate tra i monti, sopratutto nelle Alpi ma non solo.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mirimonti" # the base hostname & protocol for your site, e.g. http://example.com

# Tracker
analytics: UA-64322985-11

maps_key: AIzaSyD3TxPVq9xISJNCR73GKm5wIUHijJ_fb8s

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
